### ISSUE TITLE
Add support for json output

### ISSUE THREAD

**Issue by jackmac92** [tenox7/stc#4]
I'd really like to use this in scripts which monitor the health of my syncthing devices, and json would make that much more practical.

I took a look at the source and it looks like updating `dash()` to support optional json output would be a significant diff/maybe an ugly big `if` statement. I'm up for taking a shot if that's a PR you'd be open to reviewing

**Comment by tenox7** [comment]
great idea! a PR would be awesome, please send it!

my suggestion would be not to touch `dash()` but rather do another function, `dumpJson()` or something like that, invoke it as a case of switch flag.Arg(0)

thanks!!
